[package]
name = "rust-googleapis"
version = "0.0.7"
authors = ["DazWilkin <dazwilkin@users.noreply.github.com>"]
edition = "2018"

[build-dependencies]
git2 = "0.13.1"
protoc-rust-grpc = "0.6.2"

[dependencies]
protobuf = "2.8.2"
grpc = "0.6.2"
